### PR TITLE
Port command to use AbstractCommand

### PR DESCRIPTION
**Pull request by dduugg**
I came across this command via https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/cmd/services_spec.rb , which is an unusual, cross-repo test. Let's see if this works.

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Makes sense to me, thanks @dduugg!

**Comment by stianjensen** [comment]
I'm now seeing build issues that started today and seem related to this:
```
==> Tapping homebrew/services
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 2768, done.        
remote: Counting objects: 100% (461/461), done.        
remote: Compressing objects: 100% (182/182), done.        
remote: Total 2768 (delta 301), reused 379 (delta 274), pack-reused 2307        
Receiving objects: 100% (2768/2768), 746.06 KiB | 9.95 MiB/s, done.
Resolving deltas: 100% (1338/1338), done.
Tapped 1 command (48 files, 935.1KB).
Error: cannot load such file -- abstract_command
```

Is this something wrong on my end that need updating?

**Comment by SMillerDev** [comment]
What does your `brew config` say?

**Comment by stianjensen** [comment]
```
> brew config
HOMEBREW_VERSION: 4.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: b3751bca8c4a3c76107d5aa3b75b81db93cf4bb6
Last commit: 3 months ago
Core tap JSON: 09 Jan 23:20 UTC
Core cask tap JSON: 09 Jan 23:20 UTC
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
Homebrew Ruby: 3.1.4 => /opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: octa-core 64-bit dunno
Clang: 15.0.0 build 1500
Git: 2.43.0 => /opt/homebrew/bin/git
Curl: 8.1.2 => /usr/bin/curl
macOS: 14.1-arm64
CLT: 15.1.0.0.1.1700200546
Xcode: 15.2 => /Applications/Xcode-15.2.app/Contents/Developer
Rosetta 2: false
```

I've been running with `HOMEBREW_NO_AUTO_UPDATE=1` (for performance, and also to avoid daily updates breaking my build), but it seems like re-enabling updates today resolves the issue for me!

**Comment by MikeMcQuaid** [comment]
> to avoid daily updates breaking my build

ironically: setting this broke your build 😉

**Pull request merged**
