### PR TITLE
Update services help text

### PR DESCRIPTION
**Pull request by EricFromCanada**
Format to match other docs and append colons to command specs.

### CODE REVIEW

**Comment by EricFromCanada** [comment]
This PR relates to Homebrew/brew#5027.

**Comment by MikeMcQuaid** [comment]
Let's hold off merging this until https://github.com/Homebrew/brew/pull/5027 👍

**Comment by EricFromCanada** [comment]
@MikeMcQuaid Should now be good to go.

**Comment by MikeMcQuaid** [comment]
Thanks again @EricFromCanada!

**Pull request merged**
