### PR TITLE
brew services: Add pattern flag to be able to select mutliple formulars in one command

### PR DESCRIPTION
**Pull request by nicolas-heinig**
Hello there!

I thought it would be nice to be able to select formulars with a pattern.
That enables us to the following things:

1. Select multiple formulars in one command: 
  `brew services stop -p '(mysql|memcached)'` to stop mysql and memcached in one command.
2. Select a version specific fomular without the need to type the version to it:
  `brew services stop -p mysql` when you only have `mysql@5.7` installed.

Let me know what you think of my idea and implementation.

Thank you very much,
Nick

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
> 1. `brew services stop -p '(mysql|memcached)'` to stop mysql and memcached in one command.

I've not seem anyone previously request that. What's the advantage of doing it in a single command?

> 2\. Select a version specific fomular without the need to type the version to it:
>     `brew services stop -p mysql` when you only have `mysql@5.7` installed.

I definitely think this is undesirable; you could end up stopping the wrong service due to a typo.

---

Thanks for the PR anyway but I'm unsure we're going to merge this.

**Comment by nicolas-heinig** [comment]
> I've not seem anyone previously request that. What's the advantage of doing it in a single command?
I found myself often in the position where I would need to stop two services. After stoping the first one I would need to type the command again. You could have the same convenience when you are able to provide more than one formular name to the services commands. What do you think of this idea?

**Comment by nicolas-heinig** [comment]
>  You could end up stopping the wrong service due to a typo.

Hmm. Yes you are right, that's a danger of the pattern. Did you thought about adding aliasing for formulars? So that when I only run `mysql@5.7` I could reference it with simply `mysql` ?

**Comment by MikeMcQuaid** [comment]
Sorry @nicolas-heinig, passing on this.

**Pull request closed without merging**
