### PR TITLE
`run_at_load` integration

### PR DESCRIPTION
**Pull request by DenizUgur**
Continuation of https://github.com/Homebrew/brew/pull/14624

### CODE REVIEW

**Comment by DenizUgur** [comment]
@SMillerDev TL;DR, we might need to use `OnActiveSec` and `systemctl enable --now <service_name>.timer` when `run_at_load` is false. Since unit doesn't get activated `OnUnitActiveSec` might not be the right property here.

I'm trying several combinations of systemd calls [here](https://github.com/DenizUgur/containerized-systemd). I haven't been able to replicate how homebrew loads the systemd but that might be something wrong with my [setup](https://github.com/DenizUgur/containerized-systemd/blob/master/tests/interval-positive.sh).

However, I'm confident that in order to not start the unit file but follow the timer we may have to load the service like [this](https://github.com/DenizUgur/containerized-systemd/blob/master/tests/interval-negative.sh). I would very much appreciate if you could also verify this behaviour.

**Review by MikeMcQuaid — COMMENTED** [review]
Makes sense to me so far but deferring to @SMillerDev

**Comment by DenizUgur** [comment]
@SMillerDev kindly bumping this PR as well

**Comment by SMillerDev** [comment]
Here's a crazy idea. Could we let systemd run itself with a delay using https://wiki.archlinux.org/title/Systemd/Timers#Transient_timer_units?

**Comment by DenizUgur** [comment]
Are there any functional tests to see whether these delays are working accordingly?

**Comment by SMillerDev** [comment]
There are not, but if we want to add this feature we should probably have some

**Comment by DenizUgur** [comment]
Okay, the tests for this shouldn't be a big problem but I would need a bottle with reconfigurable service block. If you could guide me on that then I can try to come up with something.

**Tests**
- Run command: Regardless of `run_at_load` it should run it but not enable it. Not exactly sure how this could be done for macOS though but I'm sure it's not really a big problem.
- Start command: If `run_at_load`, then start and enable it. Else, don't start but enable the timer explicitly.

**Comment by SMillerDev** [comment]
Maybe we can make a small sample formula that just creates a file as a service?

**Comment by DenizUgur** [comment]
Should we push that formula here on `spec` folder or the core repository?

**Comment by SMillerDev** [comment]
I think we can create a file on the build node just for the tests.

**Comment by DenizUgur** [comment]
@SMillerDev can you review the current code so far? I don't think I'm getting the default true `run_at_load`.

**Comment by SMillerDev** [comment]
Code looks fine, are you testing this with `brew services info`?

**Comment by DenizUgur** [comment]
I'm not testing with anything right now. I just tried to change this method to return `false` manually but it still assumes it's `true`. That's why I'm not exactly sure I did this correctly.

https://github.com/Homebrew/homebrew-services/blob/302a43f642d3dbd5986434a3e35d2bd66d2d3ba6/lib/service/formula_wrapper.rb#L42-L44

**Comment by MikeMcQuaid** [comment]
@DenizUgur What's blocked here?

**Comment by DenizUgur** [comment]
My lack of knowledge of this repository to be honest. I don't think I understand how it really works (Ruby wise). The lack of testing environment also blocks me.

**Comment by MikeMcQuaid** [comment]
@DenizUgur Sorry to hear that! If you can ask more specific/direct questions for help from @SMillerDev and myself: we'll do what we can to help.

**Comment by MikeMcQuaid** [comment]
Ok, closing this out for now. Feel free to bump this when you're able to work on it a bit more.

**Pull request closed without merging**
