### PR TITLE
Revert "Added support for running services fully backgrounded on macOS"

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
Reverts Homebrew/homebrew-services#512
Fixes https://github.com/Homebrew/brew/issues/14078

Sorry @GottemHams, another revert needed.

### CODE REVIEW

**Comment by GottemHams** [comment]
Hmm, well that's a new one. I had to figure this one out myself too. I followed the same steps erwinrachim wrote about:
> but this happens when we restart our mac and the service has been running before.
> so after i did the experiment:
>
>    the service has not been run or "none"
>    I did brew services start httpd
>    and I tried brew service stop httpd : no problem, it works
>    I did again brew services start httpd
>    restart mac
>    and try again brew services stop, and it will take a very long time to stop

**Before** rebooting I actually changed the installed plist to comment out the `Aqua` session type, while the service was already running under the `user` domain. After the reboot I checked the macOS `Console` > `Log Reports` > `launchd.log` and noticed:
`(gui/503 [100005]) <Notice>: Bootstrap by otherbsd[1000] for /Users/mybrew/Library/LaunchAgents/homebrew.mxcl.httpd.plist failed (134: Service cannot load in requested session)`

So apparently it doesn't retain the domain it was originally started with, but insists on using what's appropriate for an `Aqua` session. ._. Putting `Background` before `Aqua` doesn't matter either, it still uses `gui` in that case.

As for "taking a very long time to stop", that's not actually the case. It looks like `brew services` is withholding a `boot-out failed` error message for some reason, since manually running `launchctl bootout user/503 /Users/mybrew/Library/LaunchAgents/homebrew.mxcl.httpd.plist` (what `brew services stop` does) produces an error without delay:
```
Boot-out failed: 113: Unknown error: 113
Could not find service.
```

Running it with `gui/503` instead results in `httpd` stopping properly. If I then run `brew services stop httpd` again it immediately (and correctly) reports `Warning: Service `httpd` is not started`.

Perhaps the only real way to fix it is to replace the current plist with a wrapper of sorts, which would then in turn look at a config somewhere for enabled services to auto-start. That way you can always pass along an explicit domain.

I also happened to find [this thread](https://launchd-dev.macosforge.narkive.com/7s3ELd8z/cause-of-service-cannot-load-in-requested-session), it's from 7 years ago but the behaviour seems exactly the same (emphasis mine):
> This gets complicated. First off, **Background agents cannot rely on the presence of the user's home directory because there is code that executes only in the GUI login path which may be responsible for making that home directory available.** Think NFS home directories or OG FileVault, which both require the user to enter her password at the login window to mount/decrypt the home directory. In either of those scenarios, without the user's secret, the home directory is inaccessible.
> 
> For this reason, **launchd cannot actually support loading Background agents from the user's home directory**. This is what you're hitting.

And they do mention a solution similar to what I said:
> Have another plist inside ~/Library/LaunchAgents that does not have the LimitLoadToSession key set which runs a script which does
>
> launchctl load -S Background ~/Library/LaunchAgents/com.qrecall.scheduler.plist

Of course the `load` command would have to be replaced with the `bootstrap` call `brew services` already generates. Except it feels kind of hacky and I think it would need a pretty massive rewrite of how `brew services` currently works?

---

So I started thinking about different angles. Would it be possible to have something "external" (like a new tap/formula) that overrides functions from core Homebrew and/or `homebrew-services`? So that I can implement the necessary changes through that specific tap/formula and anyone can just install that to get the background functionality. I know Ruby supports aliasing and overriding methods no prob, but I dunno if there are limitations imposed by Homebrew (e.g. a file named `foo.rb` must have (only) a `class Foo`). Perhaps I can do some magic by messing with the values returned by the original functions and achieve the same result. Sure, it would be more hacky than the wrapper plist but at least it's out of core and entirely optional (I would prolly host it in my own repo).

**Comment by MikeMcQuaid** [comment]
Sorry @GottemHams, and @SMillerDev feel free to disagree, but I think this feature has caused too many failures for users given the demand for it for me to feel comfortable with us attempting to add it again. I think we should revert the relevant Homebrew/brew changes here too.

**Comment by SMillerDev** [comment]
I don't think there is any benefit in reverting the brew changes since that is just a piece of plist that gets written. I am a little more hesitant to keep attempting the changes here though.

**Comment by GottemHams** [comment]
That's cool, as I said I was already looking for ways outside of `homebrew-services`. I did manage to alias the `domain_target` method from my own tap, which will replace the `gui` domain with the `user` variant (and pass along anything else verbatim).

I could prolly pull the same trick for the plist rewrite in case you guys decide to revert that too. But I think keeping it has at least some benefit: in my case I can simply piggyback on it to spawn a daemon in a different context. Other people may be able to do some funky things with it as well.

**Pull request merged**
