### PR TITLE
Prevent error message when cmd is nil

### PR DESCRIPTION
**Pull request by reacuna**

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
In what situation is this `nil`? Thanks!

**Comment by reacuna** [comment]
When executing `brew services` without a command

**Comment by reacuna** [comment]
For example:
```
[system] ~ brew services
Error: Unknown command ``!
brew services
    Easily start and stop formulae via launchctl

    Integrates Homebrew formulae with OS X's launchctl manager. Services can be
(etc...)
```

**Comment by MikeMcQuaid** [comment]
Nice catch, thanks! Thanks for your contribution to Homebrew! Without people like you submitting PRs we couldn't run this project. You rock!

**Pull request merged**
